
module.exports = {
  
  // docs: [
  //     'intro'
  // ],
  security: [
    {
      type: 'autogenerated',
      dirName: 'security'
    },
  ],
  another_module: [
    {
      type: 'autogenerated',
      dirName: 'another_module'
    },
  ]
};